#https://dbafromthecold.com/2020/07/17/sql-server-and-docker-compose/
version: '3.5'

services:
  sqlserver1:
    container_name: container-sql
    build: 
      context: .
      dockerfile: Dockerfile
    ports:  
      - "15789:1433"
    env_file:
      - sqlserver.env
      - sapassword.env
    volumes: 
      - /data/sqlserver:/var/opt/mssql/
      - /data/sqlserver/data:/var/opt/sqlserver/data
      - /data/sqlserver/log:/var/opt/sqlserver/log
      - /data/sqlserver/backup:/var/opt/sqlserver/backup
    networks:
      - minha-rede

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge